### PR TITLE
Updated for Guzzle 5.2.

### PR DESCRIPTION
**Pull request by danbruce**
The current class was woefully outdated and would not work with modern versions
of Guzzle.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You need to update the require statement to `~5.0`.

**Comment by fkooman** [comment]
Thanks for your pull request!

**Comment by GrahamCampbell** [comment]
The example on the readme is now wrong btw.

**Comment by fkooman** [comment]
I was also wondering if it really needs 5.2 or that 4.x is also already enough? I'm asking this because RHEL/CentOS packages guzzlehttp/guzzle 4.1.8. I know there were big API changes going from 3 to 4, but from 4 to 5 not so much perhaps...

**Comment by GrahamCampbell** [comment]
>  I'm asking this because RHEL/CentOS packages guzzlehttp/guzzle 4.1.8.

The most common way to install guzzle is via composer. I see no reason why people wouldn't want to use composer. It's the best by a mile.

**Comment by fkooman** [comment]
Yeah, I know, but I mean for production deployments when you package all your software. That's what I usually do, I make RPM packages for everything :)

**Comment by danbruce** [comment]
I'm in the process of adding unit tests. It should be easy to confirm whether we need to depend on Guzzle 4 or 5.

**Comment by GrahamCampbell** [comment]
> I'm in the process of adding unit tests. It should be easy to confirm whether we need to depend on Guzzle 4 or 5.

Basically nobody is using guzzle 4 - not even guzzle's own plugins support guzzle 4 anymore, and it's even less supported then guzzle 3. Guzzle 3 is a kind of LTS, and Guzzle 5 is the current supported stable release.

**Comment by danbruce** [comment]
Good to know. I won't bother testing against Guzzle 4 then.

**Pull request merged**
